
<!doctype html>
<html  lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Innovations Systems Group SAC">
        <title>Sugo - Revision de intentos de fraudes </title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link id="bsdp-css" href="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet">
        
        <script src="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/locales/bootstrap-datepicker.es.min.js" charset="UTF-8"></script>

        <meta name="theme-color" content="#563d7c">
        <script type="text/javascript">
        $(document).ready(function () {
            /*$('.datepicker').datepicker({
            format: "yyyy-mm-dd",
            language: "es"
            });*/
           //$(".ui-datepicker-trigger").addClass("btn btn-success")
           $('.input-group input').each(function() {
               $(this).datepicker({
                showOn: "button",
                //buttonText: '<i class="fa fa-calendar"></i>',
                format: "yyyy-mm-dd",
                language: "es",
                //showOnFocus: ,
                //todayBtn:true
                });
               
                //$(this).datepicker('clearDates');
            });
            /*$('.datepicker').datepicker({
                format: "yyyy-mm-dd",
                language: "es"
            });*/
        });
        
        </script>
        <style type='text/css'>
            .mynavbar{
                font-size: 0.9em;
                margin-bottom: 10px
            }
            th{
               text-align:center;
            }
        </style>
    </head>
    <body>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 main-yellow border-bottom shadow-sm" >
            <h5 class="my-0 mr-md-auto font-weight-bold">SUGO | Revisión de fraudes</h5>  

            <div class="row justify-content-end">
              <div class="col col-md-auto">
              <?php if (isset($_SESSION['user']) && ($_SESSION['user']!='')){?>
                    <a href='/application/logout'>Salir</a>
                <?php }?>
              </div>
            </div>
    
        </div>  
               
        <main class="container">
            <?= $this->content ?>
        </main>
        </body>
</html>