        <h5>Resumen</h5>
        <div class="table-responsive" style='align:center; text-align:center'>
            <table class="table table-striped table-sm" style='width:50%'>
            <thead>
                <tr>
                  <th>Usuarios Únicos</th>
                  <th>Monto total en transacciones</th>
                  <th>#<th>
                </tr>
              </thead>
            <tbody>
            <?php $sumTotal = 0; $sumCnt = 0;?>
            <?php foreach($this->legend as $key => $value){?>
              <tr>
                <td><?=$key?></td>
                <td style='text-align:right'><?=number_format($value['total'],2)?></td>
                <td style='text-align:right'><?=$value['cnt']?></td>
              </tr>
              <?php 
                $sumTotal += $value['total'];
                $sumCnt += $value['cnt'];
              ?> 
            <?php }?>
            </tbody>
            <tfoot>
              <tr>
                <td style='text-align:right'><b>Totales:</b></td>
                <td style='text-align:right'><?=number_format($sumTotal,2)?></td>
                <td style='text-align:right'><?=$sumCnt?></td>
              </tr>
            </tfoot>
            </table>
        </div>