
          <form class="needs-validation" id='sandbox' novalidate>
            <div class='form'>
              <div class="row g-3 input-daterange input-group">
                <div class="col-sm-4">
                  <label for="from" class="form-label">Desde</label>
                  <input type="text" class="input-sm form-control" id="from" name='from' value="<?=(isset($this->from))?$this->from:''?>" autocomplete="off" required>
                  <div class="invalid-feedback">
                    Fecha valida requerida
                  </div>
                </div>
                <div class="col-sm-4">
                  <label for="to" class="form-label"l>Hasta</label>
                  <input type="text" class="input-sm form-control" id="to" name='to' value="<?=(isset($this->to))?$this->to:''?>" autocomplete="off" required>
                  <div class="invalid-feedback">
                    Fecha valida requerida
                  </div>
                </div>
                <div class="col-sm-4"><br>
                  <button type="submit" class="w-10 btn btn-primary btn-lg">Buscar</button>
                  <button type="button" class="w-10 btn btn-primary btn-lg">Exportar</button>
                </div>
              </div>
            </div>
          </form>
         

<!--
          <div class="span5 col-md-5" id="sandbox-container">
            <div class="input-daterange input-group" id="datepicker">
              <input type="text" class="input-sm form-control" name="start" />
              <span class="input-group-addon">to</span>
              <input type="text" class="input-sm form-control" name="end" />
            </div>
          </div>
-->
          <hr>