        <form class="needs-validation" novalidate>
            <div class='form'>
              <div class="row g-3 input-daterange input-group" id='datepicker'>
                <div class="col-sm-4">
                  <label for="desde" class="form-label"l>Desde</label>
                  <input type="text" class="input-sm form-control" id="from" name='from' value="<?=(isset($this->from))?$this->from:''?>" required>
                  <div class="invalid-feedback">
                    Fecha valida requerida
                  </div>
                </div>
                <span class="input-group-addon">to</span>
                <div class="col-sm-4">
                  <label for="desde" class="form-label"l>Hasta</label>
                  <input type="text" class="input-sm form-control" id="to" name='to' value="<?=(isset($this->to))?$this->to:''?>" required>
                  <div class="invalid-feedback">
                    Fecha valida requerida
                  </div>
                </div>
                <div class="col-sm-4"><br>
                  <button type="submit" class="w-10 btn btn-primary btn-lg">Buscar</button>
                  <button type="button" class="w-10 btn btn-primary btn-lg">Exportar</button>
                </div>
              </div>
            </div>
          </form>
          <hr>