            <div class="row row-cols-1 row-cols-md-4 mb-4 text-center">
                <div class="col">
                  <div class="card mb-3 shadow-sm">
                  <div class="card-header">
                    <h4 class="my-0 fw-normal">Tarjeta de Crédito</h4>
                  </div>
                  <div class="card-body">
                    <p>En esta seccion encontrará las ventas con una misma tarjeta de crédito y distinto e-mail.</p>
                    <button type="button" class="w-100 btn btn-lg btn-outline-primary">Ingresar</button>
                  </div>
                  </div>
                </div>
                <div class="col">
                    <div class="card mb-3 shadow-sm">
                    <div class="card-header">
                      <h4 class="my-0 fw-normal">Documento de Identidad</h4>
                    </div>
                    <div class="card-body">
                      <p>En esta seccion encontrará las ventas con un mismo documento de identidad y distinto e-mail.</p>
                      <button type="button" class="w-100 btn btn-lg btn-outline-primary">Ingresar</button>
                    </div>
                  </div>
                </div>
                <div class="col">
                    <div class="card mb-3 shadow-sm">
                    <div class="card-header">
                      <h4 class="my-0 fw-normal">Teléfono</h4>
                    </div>
                    <div class="card-body">
                      <p>En esta seccion encontrará las ventas con un mismo teléfono y distinto e-mail.</p>
                      <button type="button" class="w-100 btn btn-lg btn-outline-primary">Ingresar</button>
                    </div>
                  </div>
                </div>
                <div class="col">
                    <div class="card mb-3 shadow-sm">
                    <div class="card-header">
                      <h4 class="my-0 fw-normal">Dirección</h4>
                    </div>
                    <div class="card-body">
                      <p>En esta seccion encontrará las ventas con una misma dirección y distinto e-mail.</p>
                      <button type="button" class="w-100 btn btn-lg btn-outline-primary">Ingresar</button>
                    </div>
                  </div>
                </div>
            </div>