<style>
.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>

<div class="form-signin">


<form method='get' action='/application/login'>
    <!--<img class="mb-4" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">-->
    <h1 class="h3 mb-3 fw-normal">Acceso</h1>
    <label for="inputEmail" class="visually-hidden">Usuario</label>
    <input type="text" id="inputEmail" class="form-control" placeholder="Usuario" name='user' required autofocus>
    <label for="inputPassword" class="visually-hidden">Clave</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Clave" name='pass' required>
<!--    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>-->
    <button class="w-100 btn btn-lg btn-primary" type="submit">Acceder</button>
  </form>

  </div>
