<?= $this->partial('layout/search-form.phtml', []); ?>

        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Direcci&oacute;n<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Av. Mexico 344</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>Jiron Tejadita 334</td>
                  <td>10</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>Cl santo dominguito </td>
                  <td>2</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
              </tbody>
            </table>
          </div>
