<div class='mynavbar' >
Ir a: <a href='/fraud'>Inicio</a>
</div>
<h4>Dirección</h4>

<?= $this->partial('layout/search-form.phtml', []); ?>
<?php if (isset($this->data)) {?>
        <h5>Resumen</h5>
        <div>
            <table class="table table-striped table-sm">
            <thead>
                <tr>
                  <th>Usuarios Únicos</th>
                  <th>Monto total en transacciones</th>
                  <th>#<th>
                </tr>
              </thead>
            <tbody>
            <?php $sumTotal = 0; $sumCnt = 0;?>
            <?php foreach($this->legend as $key => $value){?>
              <tr>
                <td><?=$key?></td>
                <td style='text-align:right'><?=number_format($value['total'],2)?></td>
                <td style='text-align:right'><?=$value['cnt']?></td>
              </tr>
              <?php 
                $sumTotal += $value['total'];
                $sumCnt += $value['cnt'];
              ?> 
            <?php }?>
            </tbody>
            <tfoot>
              <tr>
                <td style='text-align:right'>Totales</td>
                <td style='text-align:right'><?=number_format($sumTotal,2)?></td>
                <td style='text-align:right'><?=$sumCnt?></td>
              </tr>
            </tfoot>
            </table>
        </div>

        <div class="row justify-content-end">
              <div class="col col-md-auto">
                <a href='/fraud/export-excel?p=address&from=<?=$this->from?>&to=<?=$this->to?>'>Exportar a Excel</a>
              </div>
            </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Direcci&oacute;n<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->nro?></td>
                  <td><?=$row->street_total?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href='/fraud/address-detail?from=<?=$this->from?>&to=<?=$this->to?>&address=<?=$row->street_total?>'>Revisar</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
<?php } ?>