<div class='mynavbar' >
Ir a: <a href='/fraud'>Inicio</a>
</div>
<h4>Dirección</h4>
<?= $this->partial('layout/search-form.phtml', []); ?>
<?php if (isset($this->data)) {?>
  <?= $this->partial('layout/resumen.phtml', ['legend' => $this->legend]); ?>


        <div class="row justify-content-end">
              <div class="col col-md-auto">
                <a href='/fraud/export-excel?p=address&from=<?=$this->from?>&to=<?=$this->to?>'>Exportar a Excel</a>
              </div>
            </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Direcci&oacute;n<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->nro?></td>
                  <td><?=$row->street_total?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href='/fraud/address-detail?from=<?=$this->from?>&to=<?=$this->to?>&address=<?=$row->street_total?>'>Revisar</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
<?php } ?>