<div class='mynavbar' >
Ir a: <a href='/'>Inicio</a> > <a href='/fraud/credit-card'>Tarjeta de Crédito</a>
</div>
<h4>Tarjeta de Crédito <?=$this->card[0]?>-<?=$this->card[1]?></h4>

          <div class="container form">
            <div class="row justify-content-end">
              <div class="col col-md-auto">
                <a href='/fraud/export-excel?p=credit-card-detail&from=<?=$this->from?>&to=<?=$this->to?>&card=<?=$this->card[0]?>-<?=$this->card[1]?>'>Exportar a Excel</a> | 
                <label for="sortby" class="form-label">Ordenar por</label>
                <select class="form-select" id="sortby" required>
                  <option value="">---</option>
                  <option value="email">Correo</option>
                  <option value="nombre">Nombre</option>
                  <option value="apellido">Apellido</option>
                </select>
              </div>
            </div>
          </div>
          
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th><a href=''>Fecha &and; &or;</a></th>
                  <th>Id Orden</th>
                  <th><a href=''>Correo &and; &or;</a> </th>
                  <th>Nombre</th>
                  <th>Apellido</th>
                  <th>Monto</th>
                  <th>Cant. SKUs</th>
                  <th>Total SKUs</th>
                </tr>
              </thead>
              <tbody>
            <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->creationdate->format('Y-m-d H:i:s')?></td>
                  <td><?=$row->orderid?></td>
                  <td><?=$row->email?></td>
                  <td><?=$row->clientefirstname?></td>
                  <td><?=$row->clientelastname?></td>
                  <td><?=$row->totalvalue?></td>
                  <td><?=$row->cantsku?></td>
                  <td><?=$row->totalsku?></td>
                </tr>
            <?php }?>
                
              </tbody>
            </table>
          </div>
