<?= $this->partial('layout/search-form.phtml', []); ?>
<?php if (isset($this->data))
     print_r($data);?>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th># de Tarjeta</th>
                  <th>Tipo de Tarjeta</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1234...4563</td>
                  <td>VISA</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234...4563</td>
                  <td>VISA</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234...4563</td>
                  <td>MasterCard</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234...4563</td>
                  <td>VISA</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234...4563</td>
                  <td>American Express</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234...4563</td>
                  <td>Mastercard</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
              </tbody>
            </table>
          </div>
