<?= $this->partial('layout/search-form.phtml', []); ?>
<?php if (isset($this->data)) {?>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th># de Tarjeta</th>
                  <th>Tipo de Tarjeta</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
<?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->cardfirstdigits?>..<?=$row->lastdigits?></td>
                  <td><?=$row->paymentsystemname?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href='/fraud/credit-card-detail?from=<?=$this->from?>&to=<?=$this->to?>&card=<?=' ' + $row->cardfirstdigits+'|'+$row->lastdigits ?>'>Revisar</a></td>
                </tr>
<?php } ?>
                
              </tbody>
            </table>
          </div>
<?php } ?>
