<?= $this->partial('layout/search-form.phtml', []); ?>
<?php if (isset($this->data)) {?>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Documento de Identidad<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->clientedocument?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href=''>Revisar</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
<?php }?>
