<div class='mynavbar' >
Ir a: <a href='/fraud'>Inicio</a>
</div>

<h4>Documento de Identidad</h4>


<?= $this->partial('layout/search-form.phtml', ['from' => $this->from, 'to' => $this->to, 'repeat' => $this->repeat ]); ?>
            
<?php if (isset($this->data)) {?>
  <?= $this->partial('layout/resumen.phtml', ['legend' => $this->legend]); ?>


        <div class="row justify-content-end">
              <div class="col col-md-auto">
                <a href='/fraud/export-excel?p=document&from=<?=$this->from?>&to=<?=$this->to?>&repeat=<?=$this->repeat?>'>Exportar a Excel</a>
              </div>
            </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Documento de Identidad<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->nro?></td>
                  <td><?=$row->clientedocument?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href='/fraud/document-detail?from=<?=$this->from?>&to=<?=$this->to?>&document=<?=$row->clientedocument?>'>Revisar</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
<?php }?>
