<?= $this->partial('layout/search-form.phtml', []); ?>
            <div class="row justify-content-end">
              <div class="col col-md-auto">
                <a href='/fraud/export-excel?p=document&from=<?=$this->from?>&to=<?=$this->to?>'>Exportar a Excel</a>
              </div>
            </div>
<?php if (isset($this->data)) {?>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Documento de Identidad<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->clientedocument?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href='/fraud/document-detail?from=<?=$this->from?>&to=<?=$this->to?>&document=<?=$row->clientedocument?>'>Revisar</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
<?php }?>
