<?= $this->partial('layout/search-form.phtml', []); ?>

<div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Tel&eacute;fono<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1234456355</td>
                  <td>4</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234456355</td>
                  <td>3</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
                <tr>
                  <td>1234456355</td>
                  <td>2</td>
                  <td><a href=''>Revisar</a></td>
                </tr>
              </tbody>
            </table>
          </div>
