<?= $this->partial('layout/search-form.phtml', []); ?>
<?php if (isset($this->data)) {?>
<div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Tel&eacute;fono<fono</th>
                  <th>Usuarios únicos</th>
                  <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
<?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->phone?></td>
                  <td><?=$row->cnt?></td>
                  <td><a href='/fraud/phone-detail?from=<?=$this->from?>&to=<?=$this->to?>&phone=<?=$row->phone?>'>Revisar</a></td>
                </tr>
<?php }?>
              </tbody>
            </table>
          </div>
<?php } ?>
