<div class='mynavbar' >
Ir a: <a href='/'>Inicio</a> > <a href='/fraud/phone'>Teléfono</a>
</div>

<h3>Teléfono <?=$this->phone?></h3>

          <div class="container form">
            <div class="row justify-content-end">
              <div class="col col-md-auto">
                <a href='/fraud/export-excel?p=phone-detail&from=<?=$this->from?>&to=<?=$this->to?>&phone=<?=$this->phone?>'>Exportar a Excel</a>
              </div>
            </div>
          </div>
          
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Fecha 
                  <a href='<?=sprintf('/fraud/phone-detail?from=%s&to=%s&phone=%s&sf=date&sd=%s'
                            ,$this->from
                            , $this->to
                            , $this->phone
                            , (isset($this->sortDirection)?$this->sortDirection:'desc'))?>'>
                  &udarr;</a></th>
                  <th>Id Orden</th>
                  <th>Correo <a href='<?=sprintf('/fraud/phone-detail?from=%s&to=%s&phone=%s&sf=email&sd=%s'
                            ,$this->from
                            , $this->to
                            , $this->phone
                            , (isset($this->sortDirection)?$this->sortDirection:'desc') )?>'>
                  &udarr;</a></th>
                  <th>Nombre</th>
                  <th>Apellido</th>
                  <th>Monto</th>
                  <th>Cant. SKUs</th>
                  <th>Total SKUs</th>
                  <th>Dirección</th>
                </tr>
              </thead>
              <tbody>
            <?php foreach($this->data as $row) {?>
                <tr>
                  <td><?=$row->creationdate->format('Y-m-d H:i:s')?></td>
                  <td><?=$row->orderid?></td>
                  <td><?=$row->email?></td>
                  <td><?=$row->clientefirstname?></td>
                  <td><?=$row->clientelastname?></td>
                  <td><?=$row->totalvalue?></td>
                  <td><?=$row->cantsku?></td>
                  <td><?=$row->totalsku?></td>
                  <td><?=substr($row->address,0,30)?>...</td>
                </tr>
            <?php }?>
                
              </tbody>
            </table>
          </div>
